export enum ClientEvent {
    Timer = 'timer',
    RoomMessage = 'roomMessage',
    DrawHint = 'drawHint',
    ClearHint = 'clearHint',
    ErrorClick = 'errorClick',
    DifferenceFoundClick = 'differenceFoundClick',
    StopClicks = 'stopClicks',
    EndGame = 'endGame',
    UpdateDiffCount = 'updateDiffFoundCount',
    CheatMode = 'cheatMode',
    UpdatePlayers = 'updatePlayers',
    Accepted = 'accepted',
    Declined = 'declined',
    CloseWaitingDialog = 'closeWaitingDialog',
    CardCreated = 'gameCreated',
    CardDeleted = 'cardDeleted',
    CreationFinished = 'creationFinished',
    StartOfGame = 'startOfGame',
    StopCheat = 'stopCheat',
    TeammateLeft = 'teammateLeft',
    AuthentificationComplete = 'authentificationComplete',
    UpdateRoomPlayers = 'updateRoomPlayers',
    UpdateWaitingRooms = 'updateWaitingRooms',
    RoomCreated = 'roomCreated',
    GameStarted = 'gameStarted',
    MoveNextSet = 'moveNextSet',
}

export enum ServerEvent {
    Error = 'error',
    Listening = 'listening',
    Connection = 'connection',
    StartSoloGame = 'startSoloGame',
    StartGameCreation = 'startMultiGameCreation',
    CreateMultiGame = 'createMultiGame',
    JoinMultiGame = 'joinMultiGame',
    DeclinePlayer = 'declinePlayer',
    StartMultiGame = 'startMultiGame',
    MouseClick = 'mouseClick',
    ChatMessage = 'chatMessage',
    CheatMode = 'cheatMode',
    HintAsked = 'hintAsked',
    EndGame = 'endGame',
    Disconnect = 'disconnect',
    Authentification = 'authentification',
    WaitingRooms = 'waitingRooms',
    AbandonGame = 'abandonGame',
    PlayerLeft = 'PlayerLeft',
    KickPlayer = 'kickPlayer',
    QuitWaitingRoom = 'QuitWaitingRoom',
    DeleteWaitingRoom = 'DeleteWaitingRoom',
    CardsUpdated = 'cardsUpdated',
    CardDeleted = 'cardDeleted',
    RoomCanceled = 'roomCanceled',
}
